# Generated by Django 4.2.7 on 2023-11-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='address',
        ),
    ]
