# Generated by Django 4.2.7 on 2023-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='export',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='type',
            field=models.CharField(choices=[('ratings', 'Ratings'), ('movies', 'Movies')], default='ratings', max_length=20),
        ),
    ]
