# Generated by Django 4.2.7 on 2024-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_exportmodelncf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportmodelncf',
            name='file',
            field=models.CharField(default='model', max_length=200),
        ),
    ]
