# Generated by Django 4.2.7 on 2024-01-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_alter_exportmodelncf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportmodelncf',
            name='name',
        ),
    ]
