# Generated by Django 4.2.7 on 2023-11-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_count_movie_rating_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ratings_avg',
            new_name='rating_avg',
        ),
    ]
