# Generated by Django 4.2.7 on 2023-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_ratings_avg_movie_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
